SYMPTOM_TO_TYPE = {
    "headache": "pain",
    "pain": "pain",
    "fever": "pain",
    "cough": "cough",
    "cold": "cough",
    "allergy": "cough",
    "acidity": "acidity",
    "gas": "acidity",
    "constipation": "constipation",
    "diarrhea": "constipation",
    "nausea": "constipation",
    "wound": "skin",
    "skin": "skin",
    "vitamin": "vitamins",
    "supplement": "vitamins",
    "asthma": "respiratory",
    "copd": "respiratory",
    "pressure": "pressure",
    "heart": "pressure",
    "diabetes": "diabetes",
    "depression": "mental",
    "anxiety": "mental",
    "ulcer": "stomach",
    "stomach": "stomach",
    "infection": "antibotic",
}